# Generated by Django 5.1 on 2024-09-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='company',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
