# Generated by Django 5.1 on 2024-09-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_postal_code_user_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='transaction_id',
        ),
    ]
